apiVersion: v1
kind: Secret
metadata:
  name: instance-clid-preprod
  annotations:
    replicator.v1.mittwald.de/replicate-from: ai/instance-clid-preprod
data: {
  {{- if .Values.local.instance_clid }}
  "instance.clid": "{{ .Values.local.instance_clid }}"
  {{- end }}
}
